Refactor oem-build script (#430)
* Attempt automatically running as root

* Remove unnecessary --assume-yes

This script gets run with the noninteractive frontend specified from
within the packer scripts and if someone is actually running it in an
interactive situation, then we probably want to be interactive.

* Cleanup cd logic

A mix of `dirname` and `cd ..` is just confusing. Compute the root
directory of the project repo once and reuse it.

* Avoid hardcoding guest additions paths

Try to automatically detect the home directory of the user that the
script is running under. This avoids hardcoding the /home/oem path,
allowing this to run in other contexts or when the username has been
changed.

* Attempt cd early in oem-build

If there are issues switching to this directory, all kinds of wonky
things could happen and there's not much use in running the rest of the
script anyway if we won't be able to run the playbook.

diff --git a/scripts/oem-build b/scripts/oem-build
--- a/scripts/oem-build
+++ b/scripts/oem-build
@@ -27,23 +27,40 @@ error () {
 }
 
 #---
+# If running with `sudo`, returns the home directory of the user who invoked
+# `sudo`. Otherwise, returns the home directory of the current user.
+#---
+home_directory() {
+    if [ -z "$SUDO_USER" ]; then
+        echo "$HOME"
+    else
+        getent passwd "$SUDO_USER" | cut -d ':' -f 6
+    fi
+}
+
+#---
 # Installs VirtualBox Guest Additions if ISO file is present
 #---
 install_additions() {
-    local isofile=/home/oem/VBoxGuestAdditions.iso
+    local iso_file
+    local additions_dir
+    iso_file="$(home_directory)/VBoxGuestAdditions.iso"
+    additions_dir="$(home_directory)/additions"
 
-    if [ -f "$isofile" ]; then
-        mkdir /home/oem/additions
-        mount -o loop,ro "$isofile" /home/oem/additions
-
-        # Guest additions installation returns error 2 on success
-        /home/oem/additions/VBoxLinuxAdditions.run || true
-
-        umount /home/oem/additions
-        rm "$isofile"
-    else
+    if [ ! -f "$iso_file" ]; then
         user "VirtualBox Additions disk missing. Skipping installation."
+        return
     fi
+
+    mkdir "$additions_dir"
+    mount -o loop,ro "$iso_file" "$additions_dir"
+
+    # Guest additions installation returns error 2 on success
+    "${additions_dir}/VBoxLinuxAdditions.run" || true
+
+    umount "$additions_dir"
+    rm -r "$additions_dir"
+    rm "$iso_file"
 }
 
 #---
@@ -51,24 +68,31 @@ install_additions() {
 #---
 main () {
     if [ "$(id -u)" -ne "0" ]; then
-        error "Not running as root. Retry with sudo"
-        exit 1
+        user "Not running as root. Automatically retrying with sudo."
+        exec sudo "$0"
+        exit $?
+    fi
+
+    # Ensure this runs from the root directory of the Ansible git directory
+    local project_dir
+    project_dir="$(dirname "$(dirname "$(realpath "$0")")")"
+    if cd "$project_dir"; then
+        user "Running from $project_dir"
+    else
+        error "Unable to cd to $project_dir"
     fi
 
     user "Updating apt package cache"
     apt-get update
 
     user "Installing prerequisite packages"
-    apt-get install -V --assume-yes ansible git aptitude gcc make perl \
+    apt-get install -V ansible git aptitude gcc make perl \
         || error "Unable to install prerequisite packages"
 
     user "Attempting to install VBox Guest Additions"
     install_additions
 
     user "Running ansible OEM playbook"
-    # Ensure this runs from the root directory of the Ansible git directory
-    cd "$(dirname "$0")"/.. \
-        || error "Unable to cd to $(dirname "$0")/.."
     ansible-playbook -i hosts -c local -t oem oem.yml \
         || error "Playbook failed to complete successfully"
 }
