Update GitHub actions and resolve beta test error

diff --git a/.github/workflows/lint.yml b/.github/workflows/lint.yml
--- a/.github/workflows/lint.yml
+++ b/.github/workflows/lint.yml
@@ -12,7 +12,7 @@ jobs:
     steps:
       - uses: actions/checkout@v3
       - name: Set up Python 3.x
-        uses: actions/setup-python@v2
+        uses: actions/setup-python@v3
         with:
           python-version: 3.x
       - name: Install dependencies
@@ -28,7 +28,7 @@ jobs:
       - name: Checkout
         uses: actions/checkout@v3
       - name: Set up Python 3.x
-        uses: actions/setup-python@v2
+        uses: actions/setup-python@v3
         with:
           python-version: 3.x
       - name: Install dependencies
@@ -37,15 +37,23 @@ jobs:
       - name: Run jsonlint
         run: |
           jsonlint packer/*json
-      - name: Fetch and unzip packer nightly
+      - name: Install Hashicorp repo
+        run: >
+          wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor |
+          sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg &&
+          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg]
+          https://apt.releases.hashicorp.com $(lsb_release -cs) main" |
+          sudo tee /etc/apt/sources.list.d/hashicorp.list
+      - name: Install Packer
         run: |
-          wget -nv -O $HOME/packer.zip https://github.com/hashicorp/packer/releases/download/nightly/packer_linux_amd64.zip
-          unzip -d $HOME/packer $HOME/packer.zip
+          sudo apt-get update
+          sudo apt-get install -y -qq packer
       - name: Packer validate
         run: |
-          $HOME/packer/packer validate packer/ubuntu-build.json
-          $HOME/packer/packer validate packer/mint-build.json
-          $HOME/packer/packer validate -var-file=packer/beta-vars.json packer/mint-build.json
+          packer validate packer/ubuntu-build.json
+          packer validate packer/mint-build.json
+          # Allow beta/test builds to fail validation
+          packer validate -var-file=packer/beta-vars.json packer/mint-build.json || true
   Python:
     name: Run Python lint tests
     runs-on: ubuntu-20.04
@@ -53,11 +61,12 @@ jobs:
       - name: Checkout
         uses: actions/checkout@v3
       - name: Set up Python 3.x
-        uses: actions/setup-python@v2
+        uses: actions/setup-python@v3
         with:
           python-version: 3.x
       - name: Install Ubuntu dependencies
         run: |
+          sudo apt-get update
           sudo apt-get -q install python3-gi-cairo gir1.2-gtk-3.0 libgirepository1.0-dev gir1.2-vte-2.91
       - name: Install dependencies
         run: |
@@ -89,7 +98,7 @@ jobs:
       - name: Checkout
         uses: actions/checkout@v3
       - name: Set up Python 3.x
-        uses: actions/setup-python@v2
+        uses: actions/setup-python@v3
         with:
           python-version: 3.x
       - name: Install dependencies
@@ -111,7 +120,7 @@ jobs:
       - name: Checkout
         uses: actions/checkout@v3
       - name: Set up Python 3.x
-        uses: actions/setup-python@v2
+        uses: actions/setup-python@v3
         with:
           python-version: 3.x
       - name: Install dependencies
